subscription_id = "your-azure-subscription-id"
resource_group_name = "POC_test"
location = "East US"
acr_name = "your-acr-name"
aks_cluster_name = "flask-app-cluster"
node_pool_size = 2
node_pool_vm_size = "Standard_DS2_v2"
dns_prefix = "flask-app-dns"
docker_image_tag = "latest"
