name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.nitesh6 }}
        password: '${{ secrets.Venkata@1999 }}'

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: niteshcontainers.azurecr.io/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set context for AKS
      run: |
        az aks get-credentials --resource-group POC_test --name flask-app

    - name: Deploy to AKS
      run: |  
        kubectl set image deployment/flask-app-deployment flask-app=niteshcontainers.azurecr.io/flask-app:latest
        kubectl rollout status deployment/flask-app-deployment
