name: Deploy Flask App to AKS with Terraform

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Deploy infrastructure with Terraform and apply changes
  infrastructure-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1.1: Checkout Terraform code (from a subdirectory or a separate repo)
      - name: Checkout Terraform Code
        uses: actions/checkout@v2
        with:
          path: infrastructure/  # Ensure Terraform code is in the 'infrastructure' folder

      # Step 1.2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'  # Specify your required Terraform version

      # Step 1.3: Authenticate with Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 1.4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure  # Adjust if Terraform files are in a subfolder

      # Step 1.5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infrastructure

      # Step 1.6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infrastructure

  # Step 2: Build and deploy Flask app to AKS
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: infrastructure-deploy  # Ensure infrastructure is deployed before app deployment

    steps:
      # Step 2.1: Checkout application code
      - name: Checkout Flask Application Code
        uses: actions/checkout@v2

      # Step 2.2: Set up Docker Buildx (for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 2.3: Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: niteshcontainers.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 2.4: Build and Push Docker Image to ACR
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}  # Use commit SHA as image tag
          echo "Building and pushing Docker image with tag $IMAGE_TAG"
          docker build -t niteshcontainers.azurecr.io/flask-app:$IMAGE_TAG app/login
          docker push niteshcontainers.azurecr.io/flask-app:$IMAGE_TAG

      # Step 2.5: Set up AKS credentials
      - name: Set up AKS credentials
        run: |
          echo "Setting up AKS credentials"
          az aks get-credentials --resource-group POC_test --name flask-app --overwrite-existing

      # Step 2.6: Deploy to AKS by updating the image in the deployment
      - name: Update AKS Deployment
        run: |
          echo "Applying Kubernetes manifests"
          kubectl apply -f app/kubernetes/deployment.yaml
          kubectl set image deployment/flask-app-deployment flask-app=niteshcontainers.azurecr.io/flask-app:${{ github.sha }}
          kubectl apply -f app/kubernetes/my-app-service.yaml
          kubectl apply -f app/kubernetes/my-app-ingress.yaml

      # Step 2.7: Verify deployment status in AKS
      - name: Verify Deployment Status
        run: |
          echo "Checking deployment status in AKS"
          kubectl rollout status deployment/flask-app-deployment
