name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: niteshcontainers.azurecr.io  # Your ACR URL
          username: ${{ secrets.ACR_USERNAME }}  # ACR username from GitHub Secrets
          password: ${{ secrets.ACR_PASSWORD }}  # ACR password from GitHub Secrets

      - name: Build and push Docker image
        id: build_image 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: app/login/Dockerfile
          push: true
          tags: niteshcontainers.azurecr.io/flask-app:latest

      - name: Set image name
        run: echo "IMAGE_NAME=niteshcontainers.azurecr.io/flask-app:latest" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set context for AKS
        run: |
          az aks get-credentials --resource-group POC_test --name flask-app

      - name: Deploy to AKS
        run: |  
          kubectl set image deployment/flask-app-deployment flask-app=${{ env.IMAGE_NAME }}  # Use the environment variable
          kubectl rollout status deployment/flask-app-deployment
